name: Build and Deploy to Nuget

on:
  push:
    branches: [ main, dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.build.outputs.artifact }}
    steps:
      - uses: netcorext/dotnet-build-package-action@dev
        name: Build Package
        id: build
        with:
          app: "Netcorext.Extensions.Swagger"
          src: "."
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: netcorext/push-nuget-package-action@dev
        name: Push Package
        with:
          artifact: ${{ needs.Build.outputs.artifact }}
          nuget-api-url: ${{ secrets.NUGET_API_URL }}
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}